# A standard workflow to build and push a Docker image to Docker Hub

name: CI - Build and Push Docker Image

# This workflow runs on any push to the "main" branch
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    # Use a free Linux virtual machine provided by GitHub
    runs-on: ubuntu-latest-4-cores

    steps:
      # Step 1: Check out your repository code so the runner can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets you stored
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx. This step is a required helper.
      # Notice we are NOT specifying a cloud driver or endpoint.
      # It will use the local Docker engine on the GitHub runner.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build the Docker image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5 # Using v5, which is stable and widely used
        with:
          context: .  # Use the root of the repo as the build context
          file: ./Dockerfile  # OPTIONAL: Specify a different Dockerfile name if needed, e.g., ./LMSDockerfileProd
          push: true  # This actually pushes the image to the registry
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mineru-exams:latest # Replace my-app with your desired image name
